### ISSUE TITLE
Local recording in Bot Instance fails with an Exception

### ISSUE THREAD

**Issue by venkat-jeyaraman** [aws-samples/aws-virtual-participant-framework-for-rtc#35]
### Expected behavior and actual behavior

Local recording of audio should be possible in Bot instance when running the application locally on a Windows 10 home edition machine, but it fails with an Exception attached to this issue. This issue is reproducible if i run the application exe outside Visual stdio IDE in command line too.
### Steps to reproduce the problem

Run a release X64 version of the windows SDK application in Debug mode to reproduce the issue.

### Specifications like the version of the project, operating system, or hardware
Main branch. No changes made on that branch locally.
Windows 10 Pro
64-bit operating system, x64-based processor
Visual studio community - 2019 edition

![Exception_bot_local_recording](https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/assets/7836648/644d5b7a-7e51-4f00-a077-fdc611ac01d8)

**Comment by sinasojoodi** [comment]
I wonder if this is because the environment variables are not being loaded correctly when your run outside of visual studio. `kvssink` in the gstreamer pipeline[ requires the AWS credentials and other configurations to be passed in via env variables. ](https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/tree/main/virtual-participant-orchestrator-for-zoom-meeting/src#set-environment-variables).

When you run the inside docker/ECS, you can pass in the env variables to the container.  Similarly the Visual Studio knows how load the env variables (system via `SETX` or as configuration inside visual studio). I'm not sure if running .exe file stand alone is pulling the env variables correctly.

**Comment by venkat-jeyaraman** [comment]
hi @sinasojoodi thanks for the response. The issue happens if i run the application inside or outside Visual studio.  The issue i am seeing is gstreamer init is not happening properly and the element set state function is throwing memory access exception.

**Comment by venkat-jeyaraman** [comment]
ah i see what you are saying. let me think from that angle and see if it works.

**Comment by sinasojoodi** [comment]
Please also take a look at the dockerfile to see what dependencies you need to have on your system for the SDK app to run. Visual studio runtime and libraries are one such example. Gstreamer, vcpckg installed labraries are others. You won't be able to simply copy paste the .exe file to another windows machine and run it. The runtime environment has to have all of those components installed in the expected locations for the .exe file to run correctly.

**Comment by venkat-jeyaraman** [comment]
@sinasojoodi i was able to get back past the G-streamer issue by making sure GST_PLUGIN_PATH is set properly. Now i am facing other issue where Kinesis stream is not getting created at all. I dont see any errors though

**Comment by sinasojoodi** [comment]
How are you running this? using the docker on ECS? or locally on a workstation with visual studio?  you won't see any logs if you are not using either those options. With Visual Studio, if you run in debug mode a debug window will pop up and issues with Kinesis Video Stream will likely show up there.

**Comment by venkat-jeyaraman** [comment]
thanks @sinasojoodi for the response. I am running with Visual studio debugger. Will check the logs and update here. I have a question any idea when you will merge the changes to work with latest version of Zoom SDK. thanks.

**Comment by sinasojoodi** [comment]
Not yet unfortunately but definitely before the Nov deadline. Zoom is working on the additional code to make 5.14 version work

**Comment by sinasojoodi** [comment]
All the pending changes are merged in. Please open a new issue if the recommendations here are not working for you
