### ISSUE TITLE
CodePipelines failed

### ISSUE THREAD

**Issue by osamabinsaleem** [aws-samples/aws-virtual-participant-framework-for-rtc#36]
### Expected behavior and actual behavior

ANSWER:
I followed the readme file and after deployment, both of my codePipelines failed with following errors:
windows-container-cicd-pipeline
<img width="970" alt="Screenshot 2023-08-31 at 12 18 46 PM" src="https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/assets/37154675/8a53af04-053d-4ed1-8493-ebb0c9485e51">
<img width="1183" alt="Screenshot 2023-08-31 at 12 19 04 PM" src="https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/assets/37154675/b548e416-d3c8-4160-bdd7-e1a210d4c7f7">

CDKPipeline:
<img width="1183" alt="Screenshot 2023-08-31 at 12 19 37 PM" src="https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/assets/37154675/b2e2b85d-3368-4d3d-a2cc-e1f2ace066a7">

**Comment by osamabinsaleem** [comment]
these are the Cloudwatch logs of the failed lambda function: 
<img width="1183" alt="Screenshot 2023-08-31 at 1 04 54 PM" src="https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/assets/37154675/ec902ba9-8e36-475a-b603-e729ccb8e651">

**Comment by osamabinsaleem** [comment]
I managed to fix the ```windows-container-cicd-pipeline``` pipeline by creating subnets for my default VPC. however the ```CDKPipeline``` is still crashing

**Comment by osamabinsaleem** [comment]
I already had 5 VPC's in that region and AWS has a limit of 5 VPC's per region. I had to delete one VPC and then the ```CDKPipeline``` also worked.

**Comment by sinasojoodi** [comment]
Thanks for reporting, I'm re-opening to add some mention of AWS service limit (# of VPC in this case) in readme or troubeshooting doc.
