### ISSUE TITLE
CodeBuild fails due to "Unsupported engine" for node

### ISSUE THREAD

**Issue by hazelguo** [aws-samples/aws-virtual-participant-framework-for-rtc#37]
### Expected behavior and actual behavior

ANSWER:
I followed the instructions strictly, got this error from CodeBuild:
<img width="374" alt="image" src="https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/assets/15651955/5ee495fe-64b4-43b1-9a48-05d042937edb">

<img width="1368" alt="image" src="https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/assets/15651955/6f1b6638-7dc1-4c15-8422-8c8d0b6646a0">

Then I (1) upgraded my local node from 18.16 to 18.17 and (2) made changes to `package.json` to specify engine version:
<img width="295" alt="image" src="https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/assets/15651955/d908c741-9f47-4dda-8487-21d392421693">

Turns out it doesn't help at all. I still get the same error.

### Steps to reproduce the problem

ANSWER:
Just follow the instructions.

### Specifications like the version of the project, operating system, or hardware

ANSWER:
Pulled main (of this repo) today. I'm using mac m2.

**Comment by hazelguo** [comment]
I tried to update `package.json` to other values. However, that file doesn't seem to be used at all.
I also tried to update `npm install -g npm@lastest` to `npm install -g npm@18.17.1` in `zoom-meeting-bot-cdk-pipeline-stack.ts`. Then I get error `npm ERR! notarget No matching version found for npm@18.17.1.`
<img width="1387" alt="image" src="https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/assets/15651955/238b8de9-83fa-4ecb-ace9-bc9d87428346">

**Comment by hazelguo** [comment]
oh I figure it out. I change the first command in `zoom-meeting-bot-cdk-pipeline-stack.ts` to `'npm install -g node@latest --force','npm install -g npm@10.1.0'`

**Comment by sinasojoodi** [comment]
Thanks for reporting this, I think there is an issue with the latest versions of node and how it works with the project.  I'm re-opening this to update the code and also provide perscriptive guidance on version of node needed (v16) in the README.md
