### ISSUE TITLE
CodePipeline failed: PipelineAppStage-CodePipelineCustomActionStack

### ISSUE THREAD

**Issue by just-zoomit** [aws-samples/aws-virtual-participant-framework-for-rtc#40]
### Expected behavior and actual behavior

**Expected behavior** 
CodePipeline builds successfully

**Actual behavior**

The  PipelineAppStage-CodePipelineCustomActionStack build fails, even after hitting retry and attempting to redeploy the stack. The issue persists even when completely cleaned up and redeployed.

<img width="1348" alt="image" src="https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/assets/83678093/0452948b-985c-4290-988c-eb63632222db">

<img width="1322" alt="image" src="https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/assets/83678093/1d37f790-0c6c-4567-a93a-21e7c8cc5b14">

**PipelineAppStage-CodePipelineCustomActionStack: Events**
<img width="1366" alt="image" src="https://github.com/aws-samples/aws-virtual-participant-framework-for-rtc/assets/83678093/b0e45abf-1257-46b4-be30-dce1bd69ee04">

**What I tried:** 
* Clicked the “Retry” button in the UI, the “ PipelineAppStage” stage failed 
* Manually deleted the PipelineAppStage-CodePipelineCustomActionStack and re-run the deployment. However, the build still failed.
* Tried to manually create changeset, but the operation failed as well
* Tried to downgrade node and rebuild from a fresh start and the last stage still failed. 

ANSWER: 

### Steps to reproduce the problem

* Execute cdk deploy via the command line 
* Check Pipeline status via code pipeline in AWS console

ANSWER: 

### Specifications like the version of the project, operating system, or hardware

* Latest Version of AWS-VPF : [v0.2.0]-2023-07-19
* OS: macOS

ANSWER:

**Comment by sinasojoodi** [comment]
I'm going to push a fix for updating npm packages for CDK deploy,  please note you must use `node version 16` and `npm@^9`
